### ISSUE TITLE
colnames(fData(MSnSet)$Matrix)

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#24]
Add code to make colnames NULL to stop confusion when loading labels

names(colnames(fData(MSnSet)$Matrix)) <- NULL

**Comment by lgatto** [comment]
Where do you think this should that be added? This should be caught as soon as possible, as opposed to adding your line in the plotting function.

**Comment by lgatto** [comment]
Add a `names = TRUE|FALSE` argument to `flipGoTermId` and friends.

**Comment by lgatto** [comment]
See `pRoloc` commit b993cfacf61888148a5ca9fb4e029b7dd76d8454.
