### ISSUE TITLE
pRolocVis features

### ISSUE THREAD

**Issue by lgatto** [ComputationalProteomicsUnit/pRolocGUI#25]
Discussion about important and less important features is `pRolocVis`, in preparation for a new version.

**Comment by lgatto** [comment]
Input from @pierremj - thank you for your comments.

### These are the features that I find most important:
* Being able to see the name of the proteins in the PCA plot when I hover/click. Trying to figure out the proteins in a specific location of the plot with the common R methods is very annoying (even if I use interact()). This is what made me use the GUI initially.
* Being able to zoom and move through the plot
* Be able to add color. Size is also useful for looking at the category scores, but it would be nice to be able to scale the size. I don't really use shape since it is harder to distinguish shapes, at least for me.
* Highlight proteins that I click/query/search
* The protein profiles tab
* I really like the feature meta-data tab. Specially being able to filter based on the features of interest

### These are the features that could be dropped in my opinion:
* The quantitation tab, I don't really look at that tab. Usually I use the protein profiles tab.
* The sample meta-data tab
* Selecting the selections to be displayed (PCA, protein profiles, saved search, and query). I think the only one needed is some way to activate/deactivate the 'saved searches' one.
* I like the search tab, but I feel it is a little difficult to use. The "display information" part takes too much space and I don't find it useful. What I use from that tab is the Searches column on the left to save my features and display the saved ones.
* I don't use the upload option. Usually I would just pass the list with all my MSnSets when I call pRolocVis.
* The Download Plot function is nice, specially to download the plots in a vector format (.pdf). However, I feel like the users could take screenshots, so it may not be fully necessary.

**Comment by lgatto** [comment]
From the hackathon, re `pRolocVis2`:

- add hovering, to simply/quickly identify proteins on the fly
- when zooming and selecting proteins in the table, then zoom out; the table is not updated with all proteins, only those in the previous zommed region are available

**Comment by lgatto** [comment]
See also #34

**Comment by lmsimp** [comment]
Addressed in new pca app!
