### ISSUE TITLE
add new apps

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#26]
- [x] Add `pRolocVis_classification`
- [x] Add `pRolocVis_profiles`
- [x] Rename `pRolocVis2` to `pRoloc_pca`
- [x] One function that will dispatch the above (add 3 arguments to new `pRolocVis` function: `MSnSet`, `what`, `matrix`) 
- [x] Think about what to do with old `pRolocVis`. Add as `pRolocVis_legacy` or original etc.?

**Comment by lmsimp** [comment]
@lgatto I Have created a local branch to do this, once I checked all is okay will merge and push to master. Will show you on Monday.

**Comment by lgatto** [comment]
@lmsimp could you push your branch to github

**Comment by lmsimp** [comment]
@lgatto Do you have any objections to me changing the default to TRUE for the argument `all` in `pRolocVis_pca` (previously `pRolocVis2`)?

**Comment by lgatto** [comment]
Ok.
