### ISSUE TITLE
Passing pre-computed ordinance data to pRolocVis functions

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#28]
- Has these been done for both `pRolocVis` versions?
- Need to make this possible for the new Apps

**Comment by lgatto** [comment]
This is supported in `plot2D`, where `method` can be a matrix.

**Comment by lmsimp** [comment]
@lgatto I have added an argument `matrix` to `pRolocVis_classify` and `pRolocVis_profiles` if one wants to pass a pre-computed matrix. Would you rather me call this method?

**Comment by lmsimp** [comment]
Have called this `method` to keep consistent with old `pRolocVis`

**Comment by lgatto** [comment]
`method` originally served another purpose, that of choosing the dimensionality reduction method. Then, it was also used to pass a pre-computed matrix (using one method). Ideally, it would be best to support this same behaviour.
