### ISSUE TITLE
pRolocVis_pca

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#29]
Legend looks strange on my screen - not displayed properly. Need to fix this.

**Comment by lmsimp** [comment]
@lgatto Do you think we should remove the profiles tab? Is this now redundant with `pRolocVis_profiles`?

**Comment by lgatto** [comment]
Don't know. Do you have a table and can you select on the plot on `pRolocVis_profiles`?

**Comment by lmsimp** [comment]
No, you can just view profiles according to organelle selection. Hmmm let's not change anything right now then. For the future we may wish to consider search a searchable/table version for the profiles and keeping 'pca' and 'profiles' separate, as there is a small overlap at the moment.
