### ISSUE TITLE
To fix in apps

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#30]
## `pRolocVis` wrapper
- [x] Update documentation

NB: This is temporary documentation, more will come once I have written new vignette

## `pRolocVis_legacy`
- [x] `method` not working, "PCA" works fine but "MDS" and others do not

## `pRolocVis_pca`
- [x] make `all = TRUE` default
- [x] call `mrkMatToVec` transparently
- [x] `method` not working, "PCA" works fine but "MDS" and others do not
- [x] legends
- [x]  a hyphen in a `pmarkers` name previously broke the app, but this does not seem the case for me. Check on other OS's, @lgatto can you pull and see if this is the case for you? It happened on Kathryn's PC, but can't remember if this way the case for me before your fix
- [x] @lgatto What do you think about changing name of sidebar 'Markers' to 'Input' something more general?
- [x] axes labels on profiles tab
- [x] Add `narrowFeatureData` so most relevant features are viewed in the table

## Other
- [x] Check NAMESPACE

**Comment by lgatto** [comment]
@lmsimp I have moved `selectFeatureData` to `MSnbase`, as I think it is handy in other situations. It has a `shiny` or a simple text interface.

**Comment by lmsimp** [comment]
@lgatto Plan to add an argument to `pRolocVis_pca` called `fdInd` or similar (suggestions? `fdsel`, `fdataInd`?) to pass feature data indices to `selectFeatureData`,  so that it is possible to load the desired columns for the data table in the PCA app. If not specified the function will just use `narrowFeatureData`

**Comment by lmsimp** [comment]
Just looked at `selectFeatureData` would be nice to add an argument so a vector corresponding to column numbers to keep can be passed (what you call `k` in your function)

**Comment by lgatto** [comment]
> Plan to add an argument to `pRolocVis_pca` called `fdInd` or similar (suggestions? `fdsel`, `fdataInd`?) to pass feature data indices to `selectFeatureData`, so that it is possible to load the desired columns for the data table in the PCA app. If not specified the function will just use `narrowFeatureData`

No such plans. There could be a message that, when `narrowFeatureData` is called, it informs the user that a subset of feature data has been selected and that they can use `selectFeatureData` to choose the appropriate ones manually.

> It would be nice to add an argument so a vector corresponding to column numbers to keep can be passed (what you call k in your function)

Good idea, will do that.

**Comment by lmsimp** [comment]
Sorry I wasn't clear, **I** would like to add an argument as suggested above. Do you have objections and if no, what do you think I can call this argument (suggestions above).

At the moment there is no warning when the PCA app is loaded to say the table only displays 12 columns of the `fData`. We could add one.

**Comment by lmsimp** [comment]
Can you please let me know when you have added `k` to `selectFeatureData`. Thanks.

**Comment by lgatto** [comment]
See MSnbase 1.19.3.

Good idea re warning - maybe `narrowFeatureData` could have a `message` added (rather than warning).

**Comment by lmsimp** [comment]
> Plan to add an argument to `pRolocVis_pca` called `fdInd` or similar (suggestions? `fdsel`, `fdataInd`?) to pass feature data indices to `selectFeatureData`,  so that it is possible to load the desired columns for the data table in the PCA app. If not specified the function will just use `narrowFeatureData`

Is this okay?

**Comment by lgatto** [comment]
Ok, if you wish. 

(I have renamed `k` to `fcol` in `selectFeatureData`, for consistency)

**Comment by lmsimp** [comment]
I think we are almost ready to merge

**Comment by lmsimp** [comment]
>  Check how applications look on different screens and OS, adjust default figure margins appropriately

On the students PCs no labels on the x-axis of the off the box plots in the classify app were visible
