### ISSUE TITLE
legacy model

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#31]
@lgatto What to do about this model and associated documentation. 

Do you plan to keep the original `legacy` app and documentation? We now have `pca` so I'm not sure it's needed, we could depreciate it? Or would you like to keep it but not export?

If keep, what about the documentation? This needs to be updated with new function names etc.

**Comment by lgatto** [comment]
The documentation/vignette would need to be trimmed down to include only the GUI bits and replace `pRolocVis` with `pRolocVis_legacy` (or what about `_v1`?). We could also deprecate it, indeed, but still export it along all the other apps. We could discuss this and go over the docs tomorrow, if unsure.

**Comment by lmsimp** [comment]
The other apps are not exported, but `pRolocVis` wrapper function is exported. Yes, let's discuss tomorrow, in the meantime I will do minimal updates the old documentation, think about nice use cases to display apps for application note and Monday's lab meeting
