### ISSUE TITLE
[New app] Compare application

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#32]
* New compare app to replace existing one
* Would be similar to current `pca` app to keep same style

**Comment by lgatto** [comment]
A suggestion:

![fig](https://cloud.githubusercontent.com/assets/384198/10886542/5d4aa5fc-817a-11e5-8d73-e5825091a749.png)

- the feature data table would be controlled by a radio button
- one legend is enough, as we'll keep the same proteins and hence classes
- need to be able to select/zoom and select rows in table, like PCA app
- each selection/zooming is reflected in both columns

**Comment by lmsimp** [comment]
I really like the above design. 

> * the feature data table would be controlled by a radio button
So we wouldn't display the table all the time?

> * need to be able to select/zoom and select rows in table, like PCA app
> * each selection/zooming is reflected in both columns
* Selecting entries from the table and highlighting on both plots is fine
* Zooming to update table entries based on what is captured is fine, as per the current pca app
* Zooming on one plot could not be reflected on the second plot, the second plot would remain inactive?

**Comment by lgatto** [comment]
> So we wouldn't display the table all the time?

Always displayed, but from one data only. To look at the corresponding table of the other data, switch with radio button.

> Zooming on one plot could not be reflected on the second plot, the second plot would remain inactive? Just the table below would be updated?

No, the 2 plots have to be synchronised all the time. That related to our recent discussion of remapping in common data space. There is actually more to discuss for this app...

**Comment by lmsimp** [comment]
> No, the 2 plots have to be synchronised all the time. That related to our recent discussion of remapping in common data space. There is actually more to discuss for this app...
Yes, yes of course. But zooming if for selection, there is not guarantee even if in the same data space that the protein we are zooming to find appears in the same area space on the second PCA.

Do you want me to wait and for us to have another chat before starting this? Or are you happy for me to get going anyway?

**Comment by lgatto** [comment]
> But zooming to select a protein, there is not guarantee even if in the same data space that the protein we are zooming to find appears in the same area space on the second PCA.

Sure, but selection of protein will highlight it on the 2 plots, to guide zooming.

> Do you want me to wait and for us to have another chat before starting this? Or are you happy for me to get going anyway?

Go ahead! Input would be an `MSnSetList` with common features (see `commonFeatureNames`) and data are properly remapped.

**Comment by lgatto** [comment]
[Branch](https://github.com/ComputationalProteomicsUnit/pRolocGUI/tree/compare) created.

**Comment by lmsimp** [comment]
Now implemented will merge with master
