### ISSUE TITLE
Feedback from users

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#34]
Requests for improvement by users

* Option to export the data table of selected entries in `pca` app?
* Clicking to highlight individual proteins to highlight (as per old app) as well as brush and zoom.
* Option to do optimisation and classification inside `classify` app
* Lots of people would like 3D app

More
* Display id when hovering

**Comment by lgatto** [comment]
> Option to do optimisation and classification inside classify app

No

> Lots of people would like 3D app

No comment.

**Comment by lgatto** [comment]
See also issue #25

**Comment by lmsimp** [comment]
I explained that the apps are not a substitute for doing the analysis I 'pRoloc'. I also explained that to look for separation to use 'profiles' app which I got good feedback but there were several requests for vis in 3D.

**Comment by lgatto** [comment]
>  several requests for vis in 3D.  

Still no (public) comment.

**Comment by lgatto** [comment]
* Display id when hovering

**Comment by lmsimp** [comment]
All addressed in the new PCA app
