### ISSUE TITLE
[New app] Aggregation app

### ISSUE THREAD

**Issue by lgatto** [ComputationalProteomicsUnit/pRolocGUI#35]
Using data at the peptide/spectrum level, run `combineFeatures` in the background and display protein (left) and peptide-level (right) PCA plots next to each other. The user can select/search for protein/peptides and the corresponding peptides/proteomics are the highlighted on both plot.

**Comment by lgatto** [comment]
@lmsimp - this is one that we might want to add before the next release.

**Comment by lmsimp** [comment]
If you want to try @lgatto feel free but zoom is buggy - I think this works okay without the zoom in latest commit 0a344fc3a5d6dfbe11089e290f19a732e83634e9

I am now going to work on fixing the peptide plot of the RHS and only allowing zooming on protein PCA on LHS

```r
library('pRolocdata')
library("pRoloc")
library("pRolocGUI")

data("hyperLOPIT2015ms3r1psm")

fData(hyperLOPIT2015ms3r1psm)$Sequence < toupper(fData(hyperLOPIT2015ms3r1psm)$Sequence)
data <- combineFeatures(hyperLOPIT2015ms3r1psm, 
                      groupBy = fData(hyperLOPIT2015ms3r1psm)$Sequence, cv = FALSE)
pRolocGUI:::pRolocVis_aggregate(data, fcol = "markers")
```

**Comment by lgatto** [comment]
What about replacing the protein PCA plot with a clickable

![rplot001](https://cloud.githubusercontent.com/assets/384198/22785845/de5ee6a0-eecd-11e6-9b73-eed5b6493e8c.png)

showing for each protein group the number of features and the max distance between features? 
One would then, for each protein selected on the left, add/highlight the protein on the peptide plot in addition to highlighting the peptides.

**Comment by lgatto** [comment]
See [`MSnbase:::agg`](https://github.com/lgatto/MSnbase/blob/master/R/functions-MSnSet.R#L310-L324) in commit 
[695fdf4e3eebe4fc90af2cb2c3db9290f007ece1](https://github.com/lgatto/MSnbase/commit/695fdf4e3eebe4fc90af2cb2c3db9290f007ece1). Function is subject to changes.

The figure above can be reproduced with
```r
res <- agg(hyperLOPIT2015ms3r1psm, "Protein.Group.Accessions", fun = max)
library("ggplot2")
ggplot(data = res, aes(x = log10(nb_feats), y = agg_dist)) +
    geom_point() +
    geom_smooth(method = "lm")
```

**Comment by lgatto** [comment]
@lmsimp you example above, shouldn't it be 
```
pRolocGUI:::pRolocVis_aggregate(hyperLOPIT2015ms3r1psm, fcol = "markers")`
```
rather than passing the aggregated `MSnSet`?

Also, need to drop the `...` from `  prots <- combineFeatures(peps, fData(peps)[, groupBy])`.

**Comment by lmsimp** [comment]
What combine PSM straight to protein?

**Comment by lgatto** [comment]
Ah, sorry, misread that `groupBy` was peps. That's fine, thanks.

**Comment by lgatto** [comment]
If we go for the `aggvar` plot: `remap` and possibly `mirror[X|Y]` can be dropped.

**Comment by lmsimp** [comment]
## TO DO:

- [x] Clear selection not working - works fine if only PCA/table is clicked. If scatter clicked does not clear
- [ ] If keeping the text info box, it needs fixing. Currently when a point is clicked the text appears and then disappears straight away*** 
- [ ] The text box also needs to be updated when a peptide is clicked on the RHS (currently only updates when a protein is clicked on the LHS)
- [x] Need to highlight point on scatter when peptide is clicked on the right plot — DONE
- Need to add protein points to the PCA on the RHS
- Need to fix zoom

***Need to discuss with @lgatto about text box vs protein ID labels on the scatter

**Comment by lgatto** [comment]
> If keeping the text info box, it needs fixing. Currently when a point is clicked the text appears and then disappears straight away

I would prefer the protein label to be added on the `aggvar` plot.

**Comment by lmsimp** [comment]
@lgatto Yes, was going to add protein label to the `aggvar` plot but the reason why I was re-considering (or having both the label on the plot and the output text box) was because there are many points that have the same coordinates, and in this case when we click `aggvar` we will then have loads of protein ID's all on top of each other, with the text box they appear in a list (when it works!). One could argue that these points are not of interest anyway... do you still think get rid of the box? Or have both?

**Comment by lgatto** [comment]
You can leave the box for not, but I find it a bit ugly, and probably not necessary, as you say.

**Comment by lmsimp** [comment]
I have removed the box and added labels to `aggvar`

**Comment by lgatto** [comment]
>  need to discuss the best style for highlighting the protein i.e. pch, col etc for the point

A slightly bigger solid black dot (`pch = 19, cex = 1.5`) followed by `pch = 19, cex = 1, col = "red"`.

**Comment by lgatto** [comment]
Very nice, I like it!

**Comment by lgatto** [comment]
> @lgatto would you like both `mean` and `max` to be available for the table (which can clicked on/off using the usual table tab)? Or would you like a new column displayed dependent on whether `mean` or `max` is selected in the drop down menu?

I think it is better to indicate both aggregation summary statistics in the table.

**Comment by lmsimp** [comment]
@lgatto I have pushed latest changes. I think I have fixed the clear selection issues now. The last point in the todo list is to add a section in the vignette

**Comment by lgatto** [comment]
Fantastic job, @lmsimp, thank you!

**Comment by lgatto** [comment]
@lmsimp let me know when you are happy to the branch to get merged.
