### ISSUE TITLE
Request for plotMat2D

### ISSUE THREAD

**Issue by dan-night-89** [ComputationalProteomicsUnit/pRolocGUI#40]
@lmsimp would it be possible that you could include a command analogous to "mirrorX = T"/"mirrorY = T", from plot2D, in plotMat2D?

**Comment by lmsimp** [comment]
Hi @dan-night-89 this should now work. Please get the latest versions of `pRoloc` and `pRolocGUI`. Can you do the following, and try passing `mirrorX` as below and let me know if it works for you.

```r
library('devtools')
install_github("ComputationalProteomicsUnit/pRolocGUI")
library('pRolocGUI')
load('go_MSnSets.rda') ## see go_analysis folder 
plotMat2D(ccNrich, fcol = "PrelimMarkers", mirrorX= TRUE, mirrorY = TRUE)
```

**Comment by lmsimp** [comment]
Eventually, I will modify `pRolocVis` so that it can take a matrix as input in the `fData` and we can visualise the GO terms this way.

**Comment by dan-night-89** [comment]
Thanks @lmsimp! I will have a look tomorrow

**Comment by lgatto** [comment]
Closing for now. Feel free to re-open if necessary.
