### ISSUE TITLE
pca app breaks when fData contains matrix

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#42]
Fix above - when a matrix of markers is passed data table fails

**Comment by lgatto** [comment]
Could you provide a reproducible example, as it seems to work when I try:

```r
> library("pRoloc")
> library("pRolocdata")
> library("pRolocGUI")
> data(dunkley2006)
> x <- mrkVecToMat(dunkley2006)
> pRolocVis(x)
pRolocVis(x)
Loading required package: shiny

Listening on http://127.0.0.1:7596
```
![2015-12-19-160830_1067x756_scrot](https://cloud.githubusercontent.com/assets/384198/11913903/4c1e7270-a66b-11e5-87ce-098aef377ff8.png)

**Comment by lmsimp** [comment]
I think I meant my newer compare app so will close this for now and re-open if necessary
