### ISSUE TITLE
PCA app additions/issues

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#45]
## Additions
* [x] Another tab for saving the data/features selected? (indices are returned, may change this to `MSnSet`)
* [x] ~~Option to save as a .csv or `MSnSet`~~ (removing for new - redirect such requesets to `write.exprs`)
* ~~save figure button - but what format? pdf is better, but can this be imported to ppt/word on Windows?~~

## To fix
* [X] After zooming selection is lost
* [X] When nothing is selected on plot there is an error

## Profiles
- [X] add colours
- [x] ~~add/remove colours (or profiles) when classes are selected/unselected in the left panel~~ (not sure we really want this)

**Comment by lmsimp** [comment]
@lgatto do you think that adding colours to the profiles will make the 'profiles zoo' redundant?

**Comment by lgatto** [comment]
Good points. I think getting rid of the profiles app and add colours to the profiles tab would be great.
