### ISSUE TITLE
Error in shinyapps

### ISSUE THREAD

**Issue by tnaake** [ComputationalProteomicsUnit/pRolocGUI#51]
When running https://lgatto.shinyapps.io/christoforou2015/ and switching to the protein profiles tab an error occurs when I select any entry except `all` in `feature(s) in` under `Plot`. The message popping up says: 

`Error: invalid class “MSnSet” object: exprs(.) must be a matrix`. 

Another error occurs in the `quantitation` and `feature meta-data` tab when selecting via the `Submit selection` feature: 
`
error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': Error in rownames(fData(obj[indices])) : 
  error in evaluating the argument 'x' in selecting a method for function 'rownames': Error in fData(obj[indices]) : 
  error in evaluating the argument 'object' in selecting a method for function 'fData': Error in validObject(.Object) : 
  invalid class “MSnSet” object: exprs(.) must be a matrix
Calls: [ -> [ -> validObject
Calls: cbind ... standardGeneric -> eval -> eval -> eval -> rownames
`

**Comment by lmsimp** [comment]
Yes, I get the same. @lgatto did you use an old `MSnSet` the latest `hyperLOPIT2015` dataset in `pRolocdata` is definitely a `validObject` and the `exprs` data is a `matrix`.

Maybe you can check this and deploy the dataset with the new GUI, as it is on our to-do list anyway? Or I can if you show me what's what tomorrow?

**Comment by lgatto** [comment]
Not sure what happens - nothing has changed, neither data nor code. I think we should switch to the new GUI. @lmsimp, could you push/merge.

**Comment by lgatto** [comment]
A test app, before replacing altogether - https://lgatto.shinyapps.io/test/

What do you think. The features of interest are still missing though.

**Comment by lmsimp** [comment]
What do you mean features of interest are present? `foi` is an optional argument

**Comment by lgatto** [comment]
> What do you mean features of interest are present? foi is an optional argument

There are features of interest in the current app: various TFs and interaction partners. Can drop them, but I suspect they are there because we cite them in the paper.

**Comment by lgatto** [comment]
Also, this only displays the combined data.

**Comment by lmsimp** [comment]
> A test app, before replacing altogether - https://lgatto.shinyapps.io/test/

Looks good to me

**Comment by tnaake** [comment]
I think the problem lies in the `MSnSet` used, however I don't know why the error occurs for this MSnSet. I have identied the function which causes the error: it is in .plotPlotDist, in there it's 
 `objPlotDist <- subset(obj, 
                            fData(obj)[, levPlotDist[i]] == levPlotDistOrg[i])` causing the error. 
Compare `subset(christoforou2014, subset = fData(christoforou2014)[, "markers"] == "unknown")`
with `subset(andy2011, subset = fData(andy2011)[, "markers"] == "unknown")`, `andy2011` is from `pRolocdata`

**Comment by lgatto** [comment]
Thanks, @tnaake. Indeed, `christoforou2014` is not valid. The assay data is a `data.frame` - this reminds me of a bug we fixed some time ago. Anyway, `christiforou2014` is defunct, and we use `hyperLOPIT2015` (in `pRolocdata`) now.

**Comment by lgatto** [comment]
I have pushed the new app to https://lgatto.shinyapps.io/christoforou2015. Will delete `test`
