### ISSUE TITLE
Help file for pRolocVis

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#55]
@lgatto I think it's misleading to display usage for `pRolocVis_pca` etc. in the man page as it's not exported. If I want to remove this, I will have to remove the tag `@rdname` from the code won't I? Then move **all** params to `pRolocVis.R`? Or am I just being picky?

**Comment by lgatto** [comment]
The problem with your suggestion is that there won't be a way to automatically document (and hence check) the arguments of `pRolocVis_pca` and others. One would need to write all this manually, which I think is not a good thing.

**Comment by lmsimp** [comment]
Yes, I see your point. So leave how it is?
