### ISSUE TITLE
Update documentation for new compare app

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#58]
See also #33

**Comment by lmsimp** [comment]
@lgatto I am having trouble re-generating the man file using `Roxygen`. 

- I have renamed the old `pRolocVis_compare` app [`pRolocVis_compare_legacy`](https://github.com/ComputationalProteomicsUnit/pRolocGUI/blob/compare-app/R/pRolocVis_compare_legacy.R) 
- The new compare app is now found in [`pRolocVis_compare`](https://github.com/ComputationalProteomicsUnit/pRolocGUI/blob/compare-app/R/pRolocVis_compare.R) and I have added `@rdname pRolocVis-apps` tag to the code so that the [`pRolocVis`](https://github.com/ComputationalProteomicsUnit/pRolocGUI/blob/compare-app/R/pRolocVis.R) wrapper finds it.
- I generate the man file using the following code `R --vanilla -e "library(roxygen2); roxygenize('pRolocGUI', roclets='rd')"` but the documentation does not seem to get updated? 

What am I doing wrong? I haven't merged yet, I want to make sure all docs are correct and am still updating the vignette. Sorry for the delay.

**Comment by lgatto** [comment]
That all looks correct. I have added a missing `@rdname` in `pRolocVis_legacy.R`.

**Comment by lgatto** [comment]
@lmsimp I have merge `compare-app` into `master`.
