### ISSUE TITLE
More shiny and js

### ISSUE THREAD

**Issue by lgatto** [ComputationalProteomicsUnit/pRolocGUI#64]
Useful resources:
- [`shinyjs`](https://github.com/daattali/shinyjs/blob/master/README.md) - Perform common JavaScript operations in Shiny apps using plain R code
- [`shinypod`](https://github.com/ijlyttle/shinypod) - shiny modules

**Comment by Kohze** [comment]
I worked with shinyjs in multiple applications - its simple and intuitive to show hide bars/buttons and integrate js libraries, but would suggest for pRologGUI to move directly to a index.html /JS approach.  

wrote the following tutorials about it. 
https://r.codes/ItemPreview/-KaElGC_3N_HjWlzipbb
https://r.codes/ItemPreview/-KaA9VcBH8ovnYPgwriJ
