### ISSUE TITLE
pRolocGUI compare fails if sampleNames between objects are not the same

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#67]

**Comment by lmsimp** [comment]
Will add nice error message when this happens

**Comment by lmsimp** [comment]
Done

**Comment by lgatto** [comment]
That test should be made in `pRoloc:::remap`, not in the GUI. Could you move it and revert the changes in `pRolocGUI`, please.

**Comment by lgatto** [comment]
Why did you add a NEWS entry for an old version number, not the last one?

**Comment by lmsimp** [comment]
Apologies brain was not working. Have now reverted changes here and moved to `pRoloc` instead see commit https://github.com/lgatto/pRoloc/commit/e3e7f2ab62280a30fd83d7a7ddaa2c70cfd2e0c7

Please feel free to re-open if this is not okay.

**Comment by lgatto** [comment]
> Have now reverted changes here

Please don't tell me you have done a `git reset --hard`!

**Comment by lgatto** [comment]
`git reset --hard` removes the commits from history on origin (i.e remote on github), hence now my local history is now different from `origin/master` and yours. Fortunately, this does not seem to be a problem, which is, to be honest, quite surprising - I was expecting really bad things to happen.

**Comment by lmsimp** [comment]
I thought git reset hard was okay as long as now one has pulled which I assume no one has in those few hours! What should I have done? I thought git reset soft was only if changes were local?

**Comment by lgatto** [comment]
> I assume no one has in those few hours!

I did, of course :-)

May be a soft reset, merge and then pushing (or something along these lines), so that the reset if recorded in public history.
