### ISSUE TITLE
error with PCA app from DT package

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#68]
Jake couldn't use the latest `pRolocGUI` as he kept getting an error message which was related to generating the data table in `pRolocVis` pca app. This was hard to de-bug (as are all Shiny apps) but it became apparent he needed the devel version of `DT`. I *think* `DT > 0.1.40` is needed.

**Comment by lgatto** [comment]
Indeed. I thought I had added this to the description file - sorry. Will do.

**Comment by lgatto** [comment]
done
