### ISSUE TITLE
Error with GOAnnotations matrix and pRolocVis

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#77]
This is almost certainly related to #76.

```r
library('pRoloc')
library('pRolocdata')
library('pRolocGUI')
data("hyperLOPIT2015")
hyperLOPIT2015 <- markerMSnSet(hyperLOPIT2015)
params <- setAnnotationParams(inputs = c("Mus musculus", 
                                         "UniProt/Swissprot"))
cc <- addGoAnnotations(hyperLOPIT2015, params, 
                   namespace = "cellular_component")
pRolocVis(cc, fcol = "GOAnnotations")

Error in : fcol %in% fvarLabels(object) is not TRUE
```
With `pRolocVis` looks okay to start with... but then trying to zoom, then click an item in the table results in an error with regard to `fcol`

**Comment by lmsimp** [comment]
I now can not reproduce the above error. 

But the issue I have is that if you pass a matrix of markers e.g. `fcol = GOAnnotations` then it appears as a long vector of 1's and 0's which is a bit ugly and also it's not at all informative. e.g.

![example](https://cloud.githubusercontent.com/assets/1698853/17245237/7a81c718-557d-11e6-91c4-6f253a4b80db.png)

**Comment by lmsimp** [comment]
So to fix this @lgatto  I have changed the `pRolocVis_pca` code so that any `fcol` which is a `matrix` is converted to a `vector` using `mrkMatToVec`. I do this for all columns that are a `matrix` not just the one called by `fcol` as we also have to Table Selection tab where we can select other columns. Is this okay with you?

**Comment by lmsimp** [comment]
Fixed in 2c332d39430973616fa8716f47784b46da627db0

**Comment by lgatto** [comment]
Would it not be easier to do something like
```r
fData(object) <- rbind(fData(object), fData(object)[, fcol])
fData(object)[, fcol] <- NULL
```

**Comment by lmsimp** [comment]
Dammit, yes it would be easier

**Comment by lmsimp** [comment]
I am now fixing a similar bug in `pRolocVis_comp` so will simplify things and then re-code the above..
