### ISSUE TITLE
add warning if app argument does not match

### ISSUE THREAD

**Issue by lmsimp** [ComputationalProteomicsUnit/pRolocGUI#80]
Currently, if I specify an app other than `"main"`, `"classify"` or `"compare"` there is no warning, or no default app loaded, nothing happens and no indication of what is wrong

```r
library('pRolocdata')
library('pRolocGUI')
data(hyperLOPIT2015)
pRolocVis(hyperLOPIT2015, "app")
```

**Comment by lgatto** [comment]
Here, you can use `match.arg` to support partial unambiguous matching.
