### ISSUE TITLE
Merging leftovers in code

### ISSUE THREAD

**Issue by lgatto** [ComputationalProteomicsUnit/pRolocGUI#83]
There are merging leftovers in the [code](https://github.com/ComputationalProteomicsUnit/pRolocGUI/blob/master/R/pRolocVis_pca.R#L448) that result in build errors. 

@lmsimp - could you fix, please.

**Comment by lgatto** [comment]
I think there was more than merely removing the `========`. It rather looks like everything is defined twice (`ui`, `server`, ...).

**Comment by lmsimp** [comment]
This should now be fixed in d6e96de7cada5b5d3b96fac9b0486e05a31ed096
