### ISSUE TITLE
useDevel version bug

### ISSUE THREAD

**Issue by Kohze** [ComputationalProteomicsUnit/pRolocGUI#85]
`> useDevel(TRUE)
`
in combination with R 3.3.3 produces the follow error message:

(useDevel() was suggested in https://www.youtube.com/watch?v=_VmAZF1g_O4&feature=youtu.be ) 

`Error: 'devel' version requires a more recent R
`

![versionbug](https://cloud.githubusercontent.com/assets/16598797/23749863/89fc324e-04ca-11e7-8b23-575940a01b7e.png)

**Comment by lgatto** [comment]
If you want to use the development version of Bioconductor, you will need R devel. This is independent of `pRolocGUI` or any other package.

```r
> library(BiocInstaller)
Bioconductor version 3.5 (BiocInstaller 1.25.3), ?biocLite for help
> useDevel() ## will produce an error
Error: 'devel' version already in use
> version
               _                                                 
platform       x86_64-pc-linux-gnu                               
arch           x86_64                                            
os             linux-gnu                                         
system         x86_64, linux-gnu                                 
status         Under development (unstable)                      
major          3                                                 
minor          4.0                                               
year           2017                                              
month          02                                                
day            25                                                
svn rev        72256                                             
language       R                                                 
version.string R Under development (unstable) (2017-02-25 r72256)
nickname       Unsuffered Consequences
```
This won't always be the case; sometime, the latest R stable will do. This is because Bioconductor and R have 6 and 12 months release cycles respectively.  See https://bioconductor.org/developers/how-to/useDevel/ for more details.

**Comment by Kohze** [comment]
solved and understood - thanks ;)
