### ISSUE TITLE
suggested changes

### ISSUE THREAD

**Issue by Kohze** [ComputationalProteomicsUnit/pRolocGUI#86]
Here some of changes I would suggest after working today on the package:

-  Moving towards defensive programming ( http://adv-r.had.co.nz/Exceptions-Debugging.html ).
At the moment inputs are handled in a way that false user inputs end up redirected to standart inputs ( a "Classify" misspelling leads to opening the` "main" --> pca` component which could lead to more confusion than it should. Here my approach (I deleted the match.args in the next commit)  https://github.com/Kohze/pRolocGUI/commit/cdce034862ee441aecf7e590585fa045eede1a39

Result of a false input with that style:
![wrong entry](https://cloud.githubusercontent.com/assets/16598797/23778507/e34b5846-053a-11e7-91b0-2e9bd11311ce.png)
 
- Deleting the zoom/reset button (the zoom in functionality seems to be deleted, I can mark an area but cannot zoom in). 
- Deleting the "Table Selection" - seems redundant as the column options have place on the sidebar which makes it better accessable.  https://github.com/Kohze/pRolocGUI/commit/5eabedf5c9c952bd026ec02a08004db038f43ec4

Before: 
![spacing](https://cloud.githubusercontent.com/assets/16598797/23778802/c93b8b90-053c-11e7-8d58-438186a18d60.png)
After:
![newarrangement](https://cloud.githubusercontent.com/assets/16598797/23778807/cda36310-053c-11e7-9be3-3c52393599e4.png)

I hope that fits the direction of the pRoloc development. I have started a larger overwrite of the GUI of which I can probably share a preview after the weekend. 

Greetings,
Robin.

**Comment by lgatto** [comment]
> Re `app` inputs, here's what I get.

```r
> pRolocVis(hyperLOPIT2015, app = "foo")
Error in match.arg(app, c("main", "compare", "classify")) : 
  'arg' should be one of “main”, “compare”, “classify”
```

Which is what you emulate, with arguable a better error message, but without the `match.arg` feature that supports partial argument matching. I am not sure your option is an improvement.

> Deleting the zoom/reset button

No, this is an essential feature used by many users. If it doesn't work, please file a bug.

> Deleting the "Table Selection" 

There are cases where there are 10s of feature variable to select from. How does that fell in the side bar, given that the zoom/reset button has to stay?

**Comment by Kohze** [comment]
> Which is what you emulate, with arguable a better error message, but without the match.arg feature that supports partial argument matching. I am not sure your option is an improvement.

Just re-checked the match.arg documentation. I had the misconception that it would imply a general fallback on errors to the first input - while that is only true for NULL values.  With that in mind match.arg is as you mentioned clearly the more elegant/shorter/functional approach. 

> No, this is an essential feature used by many users. If it doesn't work, please file a bug.

I will have a closer look this evening at the zoom feature (with other browsers) and report it then in case as bug. 

> There are cases where there are 10s of feature variable to select from. How does that fell in the side bar, given that the zoom/reset button has to stay?

the zoom/reset button itself will not add any vertical space when we use the shiny splitlayout function which adds both buttons in the same line with each having half the space. 

With 10+ arguments im relatively sure that by adding a costume css we can free up the 10px padding from sidebar (on the left, the area that is white besides the grey sidebar). Then we can probably have 2 argument boxes per line. But that depends in the end very much on the style choice the team prefers.

**Comment by Kohze** [comment]
just tested the arg.math() again - for non-dev versions we should probably set `options(error = NULL)`  to not go into traceback mode everytime the error is triggered (which is default behavior with most cran packages).

**Comment by lgatto** [comment]
No, error is an option defined by the user, and has nothing to do with the package and where it comes from; it is a bad thing to fiddle with users options.

**Comment by Kohze** [comment]
> it is a bad thing to fiddle with users options.

I agree - from that perspective, we would overwrite the user's decision to see tracebacks. We can then probable close this issue. I will create a new one on the table options once I have that finished (including the css modifications).
