### ISSUE TITLE
Improving Plot Quality

### ISSUE THREAD

**Issue by Kohze** [ComputationalProteomicsUnit/pRolocGUI#88]
While testing the zoom in functionality (which works) I took a closer look and added the `Cairo package` which adds anti-aliasing to the plot. I think the result might be worth the added package dependency. I will have to do some extra testing with larger cycles in non-cairo mode to proove that its definetly better. 

to reproduce: 
```
install.packages("Cairo") 
library(Cairo)
options(shiny.usecairo = TRUE)
```

The plot now:
![screenshot_8](https://cloud.githubusercontent.com/assets/16598797/23812107/5b60a810-05d9-11e7-9ed6-c0619789b75f.png)

with Cairo
![screenshot_7](https://cloud.githubusercontent.com/assets/16598797/23812124/67b0af3e-05d9-11e7-937c-3845b525c858.png)

Zoomed in:
now: 
![screenshot_11](https://cloud.githubusercontent.com/assets/16598797/23812803/59030baa-05dc-11e7-9b85-0c631870efef.png)

with Cairo:
![screenshot_10](https://cloud.githubusercontent.com/assets/16598797/23812771/34dff044-05dc-11e7-866e-c4a9b7c1f21f.png)

https://cran.r-project.org/web/packages/Cairo/index.html

**Comment by lgatto** [comment]
That looks much better indeed. One downside I can think of is the additional system dependency. That sort of thing can be a major hurdle for many users. I would like to test `Caro` installation on a Windows computer first. What system are you on, by the way?

**Comment by Kohze** [comment]
I already have Cairo running in my shiny frapbot application. Its compatible with windows (where im currently programming with | screens are from windows) and unix systems (ubuntu where it uses x11) but I will check out where the limits/shortfalls are.

**Comment by Kohze** [comment]
Just had a look at the rProloc documentation screenshots - and it almost looks like the same quality as my +Cairo plots. It might be that there is general a difference in windows/unix plot generation (or cairo was installed on that system).  

![ss_pca1](https://cloud.githubusercontent.com/assets/16598797/23825121/1bc2c25a-0684-11e7-93bf-51843235a8fa.jpg)

**Comment by lgatto** [comment]
May be it would be possible to have `Cairo` in suggests, and only use it if available.

FYI, these screenshots were prepared on a Mac.
