### ISSUE TITLE
Error in pRolocVis when fcol = "AnyName" and not "markers"

### ISSUE THREAD

**Issue by kbarylyuk** [ComputationalProteomicsUnit/pRolocGUI#91]
When organellar markers are added to a MSnSet using `AddMarkers` with `mcol = "AnyName"` (not "markers") then `pRolocVis` with `fcol = "AnyName"` argument returns an error if a protein from the table is highlighted:

![screen shot 2017-05-15 at 15 39 58 2](https://cloud.githubusercontent.com/assets/13316340/26063785/ea9f90aa-3986-11e7-9e9d-14645b5af845.png)

```
> pRolocVis(ToxoLOPIT_12combined[, o], fcol = "Markers_u2osToTg_5bestHits")

Listening on http://127.0.0.1:6873
Warning: Error in : fcol %in% fvarLabels(object) is not TRUE
Stack trace (innermost first):
    109: stopifnot
    108: isMrkMat
    107: <Anonymous>
    106: do.call
    105: do.call
    104: highlightOnPlot
    103: renderPlot
     93: <reactive:plotObj>
     82: plotObj
     81: origRenderFunc
     80: output$pca
      3: runApp
      2: pRolocVis_pca
      1: pRolocVis
```

**Comment by lgatto** [comment]
This is not fixed in the latest version available from github:
```r
devtools::install_github("ComputationalProteomicsUnit/pRolocGUI")
```
